### ISSUE TITLE
How to create my island？

### ISSUE THREAD

**Issue by CrystalRays** [MCFT-Server/Mskyblock#16]
I can't find any command to generate a island!

You see here is no command "create".
> /skyblock
21:40:43 [INFO] [Skyblock] /skyblock <move|remove|share|invite|spawn|expulsion|list|exit|inviteall|pvp>

And if you like, I can help translate this plugin to Chinese.Can I?

**Comment by wsj7178** [comment]
Skyblocks are created when the player enters the "/skyblock" command.

And I always welcome your translations

**Comment by CrystalRays** [comment]
I had translated it into Chinese and pulled request.

I delete the Mskyblock folder and the SkyBlock folder in the folder Worlds, and now it can create island normally.Thanks.

**Comment by wsj7178** [comment]
Thank you for translating.
