### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by ghost** [MCFT-Server/Mskyblock#3]
What Command use for generate island?

**Comment by wsj7178** [comment]
@NycuRO Commands in messages.yml
Please translate it! lol

**Comment by ghost** [comment]
I'm translated but not work. Please You can help me? Or You can ADD default commands SkyBlockGenerator ( is create , is help , is invite , is generate ,is remove , is kick ) and all is perfect for plugin. 

By the way,all know this commands and best plugin with this commands :)

You can ADD pls? Not all know how use :1:
