### ISSUE TITLE
For best plugin

### ISSUE THREAD

**Issue by ghost** [MCFT-Server/Mskyblock#4]
Hello. I have one opinion. You can add OFFICIAL essentials commands of SkyBlock ? ( /is create,invite,delete,is help ) ?

Pls add all commands în english because all players this commands ...and anyone can edit commands in config :)

**Comment by wsj7178** [comment]
I added command english.
https://github.com/MCFT-Server/Mskyblock/commit/ded5285fcff5e01d7961b1f439dba40196840d67

**Comment by ghost** [comment]
Thanks so much
